"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { useSearchParams, useRouter, usePathname } from "next/navigation";
import { useEffect, useState } from "react";

export function TermsModal() {
  const [open, setOpen] = useState(false);
  const router = useRouter();
  const pathname = usePathname();

  // Check if we're on the terms path
  useEffect(() => {
    if (pathname === "/terms") {
      setOpen(true);
    }
  }, [pathname]);

  // Handle closing the modal
  const handleOpenChange = (isOpen: boolean) => {
    setOpen(isOpen);
    if (!isOpen && pathname === "/terms") {
      // Navigate back to home when modal is closed from /terms route
      router.push("/");
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <button className="text-[15px]/normal font-medium text-muted-foreground transition-all duration-100 ease-linear hover:text-foreground hover:underline hover:underline-offset-4">
          Terms & Conditions
        </button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold mb-4">Terms & Conditions</DialogTitle>
          <DialogDescription>
            <div className="text-left space-y-4 text-foreground">
              <div>
                <p className="font-semibold text-lg">1. Terms of Use</p>
                <p>By downloading and using My Game Weather, you agree to these terms and conditions.</p>
              </div>

              <div>
                <p className="font-semibold text-lg">2. Privacy Policy</p>
                <div className="space-y-2">
                  <p>Last updated: March 13, 2025</p>
                  
                  <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                  
                  <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                  
                  <p className="font-semibold mt-4">Interpretation and Definitions</p>
                  <div className="space-y-2">
                    <p className="font-medium">Interpretation</p>
                    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    
                    <p className="font-medium">Definitions</p>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc pl-6 space-y-1">
                      <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                      <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                      <li><strong>Application</strong> refers to My Game Weather, the software program provided by the Company.</li>
                      <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Vertechx Collective, Rozenstraat 69, Hilversum, 1214BR.</li>
                      <li><strong>Country</strong> refers to: Netherlands</li>
                      <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                      <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                      <li><strong>Service</strong> refers to the Application.</li>
                      <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                      <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                      <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                      <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>
                  </div>

                  <p className="font-semibold mt-4">Collecting and Using Your Personal Data</p>
                  <div className="space-y-2">
                    <p className="font-medium">Types of Data Collected</p>
                    <p>Personal Data</p>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul className="list-disc pl-6">
                      <li>Usage Data</li>
                    </ul>

                    <p>Usage Data</p>
                    <p>Usage Data is collected automatically when using the Service.</p>
                    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, unique device identifiers and other diagnostic data.</p>

                    <p>Information from Third-Party Social Media Services</p>
                    <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
                    <ul className="list-disc pl-6">
                      <li>Google</li>
                      <li>Facebook</li>
                      <li>Instagram</li>
                      <li>Twitter</li>
                      <li>LinkedIn</li>
                    </ul>
                  </div>

                  <p className="font-semibold mt-4">Use of Your Personal Data</p>
                  <p>The Company may use Personal Data for the following purposes:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li><strong>To provide and maintain our Service</strong></li>
                    <li><strong>To manage Your Account</strong></li>
                    <li><strong>For the performance of a contract</strong></li>
                    <li><strong>To contact You</strong></li>
                    <li><strong>To provide You</strong> with news and offers</li>
                    <li><strong>To manage Your requests</strong></li>
                  </ul>
                  
                  <p className="font-semibold mt-4">Security of Your Personal Data</p>
                  <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>

                  <p className="font-semibold mt-4">Contact Us</p>
                  <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                  <ul className="list-disc pl-6">
                    <li>By email: info@vertechx-collective.com</li>
                    <li>By visiting: <a href="https://www.mgw.football/terms" className="text-primary hover:underline">https://www.mgw.football/terms</a></li>
                  </ul>
                </div>
              </div>
              <p className="text-sm text-muted-foreground mt-6">Last updated: March 13, 2025</p>
            </div>
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
} 